input {
  beats { port => 5044 }
}

filter {
  # ---------- PAYLOAD ----------
  if [event_type] == "apim_payload" and [message] =~ /LogMediator/ and [message] =~ /Payload:/ {

    grok {
      match => {
        "message" => [
          "\[%{TIMESTAMP_ISO8601:log_ts}\]\s+%{LOGLEVEL:level}\s+\{%{DATA:logger}\}\s+-\s+\{api:%{DATA:api_raw}\}\s+To:\s+%{DATA:to},\s+MessageID:\s+%{DATA:message_id},\s+correlation_id:\s+%{DATA:correlation_id},\s+Direction:\s+%{WORD:flow},\s+MESSAGE\s=\s%{WORD:message_label},\s+Payload:\s+%{GREEDYDATA:payload_raw}$",

          "^\[%{TIMESTAMP_ISO8601:log_ts}\]\s+%{LOGLEVEL:level}\s+-\s+LogMediator\s+\{api:%{DATA:api_raw}\}\s+To:\s+%{DATA:to},\s*(WSAction:\s*%{DATA:ws_action},\s*)?SOAPAction:\s*%{DATA:soap_action},\s*MessageID:\s*%{DATA:message_id},\s*correlation_id:\s*%{DATA:correlation_id},\s*Direction:\s*%{WORD:flow},\s*MESSAGE\s=\s%{WORD:message_label},\s*Payload:\s*%{GREEDYDATA:payload_raw}$"
        ]
      }
    }

    dissect {
      mapping => { "api_raw" => "%{api_name}:v%{api_version}" }
      tag_on_failure => ["_dissect_api_failed"]
    }

    json {
      source => "payload_raw"
      target => "payload"
      skip_on_invalid_json => true
    }

    if [payload][creditCardNumber] { mutate { update => { "[payload][creditCardNumber]" => "***MASKED***" } } }
    mutate {
      gsub => [
        "payload_raw", "(\"creditCardNumber\"\\s*:\\s*\").*?(\")", "\\1***MASKED***\\2",
        "payload_raw", "(\"Authorization\"\\s*:\\s*\").*?(\")", "\\1***MASKED***\\2"
      ]
    }

    date {
      match   => ["requestTimestamp", "ISO8601"]
      target  => "@timestamp"
      timezone => "UTC"
    }

    mutate {
      copy => { "to" => "request_path_or_url" }
      add_field => {
        "event_type_parsed" => "apim_payload"
      }
    }
  }

  # ---------- METRICS ----------
  else if [event_type] == "apim_metrics" {
    grok {
      match => [
        "message",
        "%{GREEDYDATA:UNWANTED}\ apimMetrics:%{GREEDYDATA:apimMetrics}\, %{GREEDYDATA:UNWANTED} \:%{GREEDYDATA:properties}"
      ]
    }
    json { source => "properties" }

    date {
      match   => ["requestTimestamp", "ISO8601"]
      target  => "@timestamp"
      timezone => "UTC"
    }
  }
}

output {
  # ---------- PAYLOAD ----------
  if [event_type_parsed] == "apim_payload" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "apim_payload-%{+YYYY.MM.dd}"
    }
  }

  # ---------- METRICS ----------
  if [apimMetrics] == " apim:response" {
    elasticsearch { hosts => ["http://elasticsearch:9200"] index => "apim_event_response" }
  } else if [apimMetrics] == " apim:faulty" {
    elasticsearch { hosts => ["http://elasticsearch:9200"] index => "apim_event_faulty" }
  }

  # stdout { codec => rubydebug }
}
